CREATE TABLE db.device
(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(25) NOT NULL,
location VARCHAR(25),
type VARCHAR(25),
description VARCHAR(25),
latitude VARCHAR(25),
longtitude VARCHAR(25),
PRIMARY KEY (id)) ENGINE=InnoDB